version: "3.8"

services:
  app:
    container_name: team-project-durian-backend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    networks:
      - proxy_default
      - database

networks:
  proxy_default:
    external: true
  database:
    external: true
