name: Deployment

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, fakepng]
    steps:
      - uses: actions/checkout@v3
      - name: Run Container
        run: docker compose -p team-project-durian-backend up -d --no-deps -V --build --force-recreate
        env:
          NODE_ENV: production

      - name: Clean Unused Images
        run: docker image prune -f
